ERRMOT.LS      Robot Name ROBOT 21-APR-21 00:55:46  

1" 21-APR-21 00:43:56 " MCTL-014 Waiting for Servo ready                  " MCTL-014 Waiting for Servo ready                  " WARN                          00000000" 
2" 21-APR-21 00:43:54 " MCTL-014 Waiting for Servo ready                  " MCTL-014 Waiting for Servo ready                  " WARN                          00000000" 
3" 21-APR-21 00:43:54 " MCTL-014 Waiting for Servo ready                  " MCTL-014 Waiting for Servo ready                  " WARN                          00000000" 
4" 21-APR-21 00:40:38 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
